config/routes.rb
OnAppTask::Application.routes.draw do

  
  controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
  end

  resources :statuses

  resources :departments

  resources :users

  resources :tickets
  match "/tickets_new" => "tickets#index_new"
  match "/tickets_open" => "tickets#index_open"
  match "/tickets_onhold" => "tickets#index_onhold"
  match "/tickets_closed" => "tickets#index_closed"
  match "/search" => "tickets#search"
  match "/statuses" => "statuses#index"

end

app/models/ticket.rb
require 'mail'
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record,attribute,value)
    begin
      m = Mail::Address.new(value)
      # We must check that value contains a domain and that value is an email address
      r = m.domain && m.address == value
      t = m.__send__(:tree)
      # We need to dig into treetop
      # A valid domain must have dot_atom_text elements size > 1
      # user@localhost is excluded
      # treetop must respond to domain
      # We exclude valid email values like <user@localhost.com>
      # Hence we use m.__send__(tree).domain
      r &&= (t.domain.dot_atom_text.elements.size > 1)
    rescue Exception => e   
      r = false
    end
    record.errors[attribute] << (options[:message] || "is invalid") unless r
  end
end

class Ticket < ActiveRecord::Base
  validates :customer_email, :presence => true, :email => true
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
 
  # GET /tickets
  # GET /tickets.xml
  def index
     set_tab :list
    @tickets = Ticket.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tickets }
    end
  end
  
  def index_new
    set_tab :list_new
    @tickets = Ticket.where(:status => 1)
    
    respond_to do |format|
      format.html {render :action => "index"}
      format.xml  { render :xml => @tickets }
    end
  end
  
  def index_open
     set_tab :list_open
    @tickets = Ticket.where(:status => [1,2,3])
    
    respond_to do |format|
      format.html {render :action => "index"}
      format.xml  { render :xml => @tickets }
    end
  end
  
  def index_onhold
     set_tab :list_onhold
    @tickets = Ticket.where(:status => 3)
    
    respond_to do |format|
      format.html {render :action => "index"}
      format.xml  { render :xml => @tickets }
    end
  end
  def index_closed
     set_tab :list_closed
    @tickets = Ticket.where(:status => [4,5])
    
    respond_to do |format|
      format.html {render :action => "index"}
      format.xml  { render :xml => @tickets }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.xml
  def new
    @ticket = Ticket.new
    @ticket.number = number_plus_one(Ticket.find(:last, :select => "number").number)
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ticket }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.xml
  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])
    @changes = Change.find(:all, :order => "id")
    @statuses = Status.find(:all)
    @owners = User.find(:all)
    
  end
  
  # POST /tickets
  # POST /tickets.xml
  def create
    @ticket = Ticket.new(params[:ticket])
    respond_to do |format|
      if @ticket.save
        Notifier.ticked_created(@ticket).deliver
        format.html { redirect_to(:action => "edit",:id => @ticket.id, :notice => 'Ticket was successfully created.') }
        format.xml  { render :xml => @ticket, :status => :created, :location => @ticket }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @ticket.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.xml

  def update
    @ticket = Ticket.find(params[:id])
    @change = Change.new
    @change.ticket_id   = params[:id]
    
    @change.owner_old   = @ticket.owner
    @change.status_old  = @ticket.status
    @change.user        = session[:user_id]
    @ticket.owner       = params[:ticket]["owner"]
    @ticket.status      = params[:ticket]["status"]
    @change.owner_new   = params[:ticket]["owner"]
    @change.status_new  = params[:ticket]["status"]
    @change.reply_text  = params[:change]["reply_text"]
    
  
  respond_to do |format|
    if @ticket.save and @change.save
      Notifier.ticket_updated(@ticket,@change).deliver
      format.html { redirect_to( :action => "edit", :id => @ticket.id, :notice => 'Ticket was successfully updated.') }
      format.xml  { head :ok }
    else
      format.html { render :action => "edit" }
      format.xml  { render :xml => @ticket.errors, :status => :unprocessable_entity }
    end
  end 
  end
  
  # DELETE /tickets/1
  # DELETE /tickets/1.xml
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to(tickets_url) }
      format.xml  { head :ok }
    end
  end
  # POST /search
  
  def search
    @ticket = Ticket.find_by_number(params[:number])
    if @ticket
      redirect_to( :action => "edit", :id => @ticket.id, :notice => 'Ticket was successfully updated.')
    else 
      redirect_to( :action => "index")
    end
  end
  def number_plus_one(number)
   # TODO: Rewrite method to autoincrement literals ex. AAB, AAC
   number=number.from(4)
   number=Integer(number.delete! "0")+1
   length=number.to_s.length
   if length > 5 then
        number.to_s
     else
        padded='AAA-' + '0' * (6-length)  + number.to_s
   end
  end
  
  
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def get_status_by_id(id)
    if id
      Status.find(id).name
    else
      return " - "
    end
  end
  def get_owner_by_id(id)
    if id
      User.find(id).name
    else
      return " - "
    end
  end
  def get_department_by_id(id)
    if id
    Department.find(id).name
    else
      return " - "
    end
  end
  def departments_select_field
    @departments = Department.find(:all)
    collection_select(:ticket, :department, @departments, :id, :name, :class => "status") 
  end
end

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>
      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :number %>
    <h3><%= @ticket.number %></h3>
  </div>
  <div class="field">
    <%= f.label :customer_name %><br />
    <%= f.text_field :customer_name %>
  </div>
  <div class="field">
    <%= f.label :customer_email %><br />
    <%= f.text_field :customer_email %>
  </div>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :department %><br />
    <df> <%= departments_select_field  %></df>
    <%= f.hidden_field :status %>
  </div>
  <div class="field">
    <%= f.label :request_text %><br />
    <%= f.text_area :request_text %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/_reply_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="left_block">
<dl>
  
  <df><h3><%=@ticket.number %></h3></df>
  
  <dt>Customer Name</dt>
  <df><%=@ticket.customer_name %></df>
  
  
  <dt>Customer Email</dt>
  <df><%=@ticket.customer_email %></df>
  
  <dt>Subject</dt>
  <df><%=@ticket.subject %></df>
  
  <dt>Request Text</dt>
  <df><%= @ticket.request_text %></df>
  
  <dt>Department</dt>
  <df><%= get_department_by_id(@ticket.department) %></df>
  
  <dt>Change status to:</dt>
  <df>
    <%= collection_select(:ticket, :status, @statuses, :id, :name, :class => "status")  %>
  </df>
  
  <dt>Reassign ticket to:</dt>
  <df>
    <%= collection_select(:ticket, :owner, @owners, :id, :name, :class => "owner")  %></df>
  <dt>Reply Text</dt>
  <df>
    <%= text_area(:change, :reply_text, :cols => 40, :rows => 20) %>
  </df>
</dl>
  <div class="actions">
  <% if session[:user_id]%>  
    <%= f.submit %>
    <% else  %>
    You must <%=link_to "login", login_url %> to reply
  <%end%>
  </div>
</div>

<div class="right_block">
  <h2>History:</h2>
  <% @changes.each do |change| %>
  <p> <b>Owner:</b> <%= get_owner_by_id(change.owner_old) %> | Status: <b><%= get_status_by_id(change.status_old) %> </b></p>
  <p><b><%= get_owner_by_id(change.user) %> replied:</b>
    <%=  change.reply_text %>
  </p>
  <hr/>
    <% end %>
</div>  
<div class="clr"></div>
  
<% end %>

app/views/tickets/edit.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Editing ticket</h1>

<%= render 'reply_form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1>Listing tickets</h1>

<table class="tickets_listing">
  <tr>
    <th>Number</th>
    <th>Customer name</th>
    <th>Customer email</th>
    <th>Subject</th>
    <th>Request text</th>
    <th>Department</th>
    <th>Status</th>
    <th>Owner</th>
    <th></th>
    <th></th>
  </tr>

<% @tickets.each do |ticket| %>
  <tr>
    <td><%= ticket.number %></td>
    <td><%= ticket.customer_name %></td>
    <td><%= ticket.customer_email %></td>
    <td><%= ticket.subject %></td>
    <td><%= ticket.request_text %></td>
    <td><%= get_department_by_id(ticket.department) %></td>
    <td><%= get_status_by_id(ticket.status) %></td>
    <td><%= get_owner_by_id(ticket.owner) %></td>
    <%#*<td><%= link_to 'Show', ticket </td>%>
    <td><%= link_to 'View', edit_ticket_path(ticket) %></td>
    <td><%= link_to 'Destroy', ticket, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number:</b>
  <%= @ticket.number %>
</p>

<p>
  <b>Customer name:</b>
  <%= @ticket.customer_name %>
</p>

<p>
  <b>Customer email:</b>
  <%= @ticket.customer_email %>
</p>

<p>
  <b>Subject:</b>
  <%= @ticket.subject %>
</p>

<p>
  <b>Request text:</b>
  <%= @ticket.request_text %>
</p>

<p>
  <b>Department:</b>
  <%= @ticket.department %>
</p>

<p>
  <b>Status:</b>
  <%= @ticket.status %>
</p>

<p>
  <b>Owner:</b>
  <%= @ticket.owner %>
</p>


<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>